http:
  host: "localhost"
  port: 3001

auth:
  jwt:
    secret: "DgqOkW01ZAvJSbxI"
    expiration: "8h"

db:
  mysql:
    dialect: "mysql"
    username: "root"
    password: ""
    database: "pixel"
    host: "localhost"
    port: 3306

  mongo:
    host: "mongodb://localhost:27017"
    user: ""
    pass: ""
    dbName: "pixel"
